# language to be used by Travis CI to run the tests
language: node_js

# Node.js version to be used when testing the project
node_js:
  - "node"

# triggering the build on branch master only
branches:
  only:
    - "master"

# prevent fetch useless Git history
git:
  depth: false